CREATE TABLE Genres(
   MovieID  INTEGER  NOT NULL
  ,GenreName VARCHAR(35) NOT NULL
  ,PRIMARY KEY(MovieID, GenreName)
);
INSERT INTO Genres(MovieID,GenreName) VALUES (1268,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1146,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1240,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1172,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1109,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1241,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1212,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1048,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1291,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1276,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1113,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1256,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1223,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1132,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1047,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1043,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1130,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1012,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1200,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1140,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1258,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1244,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1103,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1155,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1042,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1037,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1295,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1018,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1242,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1274,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1255,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1243,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1169,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1098,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1137,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1199,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1148,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1072,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1236,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1154,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1110,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1298,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1214,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1024,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1014,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1205,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1269,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1067,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1248,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1077,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1141,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1193,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1039,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1115,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1196,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1278,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1165,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1016,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1029,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1234,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1253,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1054,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1180,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1252,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1289,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1232,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1004,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1095,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1036,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1185,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1198,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1089,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1010,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1118,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1167,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1076,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1279,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1222,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1009,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1046,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1138,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1056,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1260,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1097,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1044,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1017,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1264,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1049,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1038,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1040,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1033,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1119,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1238,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1194,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1100,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1002,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1166,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1247,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1064,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1083,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1034,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1061,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1020,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1158,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1125,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1203,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1073,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1217,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1055,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1090,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1023,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1285,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1051,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1287,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1135,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1288,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1058,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1144,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1101,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1159,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1254,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1063,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1164,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1181,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1150,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1060,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1191,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1277,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1280,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1152,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1182,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1045,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1019,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1078,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1147,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1162,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1015,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1093,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1188,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1224,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1126,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1030,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1149,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1184,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1008,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1175,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1163,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1294,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1233,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1170,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1292,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1091,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1068,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1231,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1145,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1197,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1106,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1139,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1131,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1206,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1213,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1192,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1153,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1105,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1092,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1220,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1225,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1251,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1117,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1151,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1035,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1136,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1161,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1226,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1250,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1245,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1084,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1209,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1195,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1121,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1052,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1257,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1104,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1283,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1286,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1099,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1102,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1239,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1237,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1178,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1229,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1270,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1028,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1124,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1031,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1027,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1088,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1300,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1025,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1179,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1080,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1177,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1290,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1221,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1057,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1094,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1176,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1204,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1059,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1282,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1281,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1013,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1133,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1086,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1215,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1066,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1160,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1261,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1262,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1189,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1123,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1011,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1156,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1207,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1065,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1071,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1273,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1026,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1230,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1005,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1111,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1263,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1201,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1112,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1228,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1299,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1087,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1271,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1122,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1202,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1107,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1235,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1293,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1069,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1096,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1128,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1062,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1022,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1007,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1134,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1246,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1143,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1186,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1085,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1297,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1208,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1127,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1001,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1120,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1129,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1173,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1142,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1006,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1210,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1265,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1021,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1003,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1108,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1114,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1190,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1050,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1267,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1216,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1211,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1249,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1041,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1082,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1070,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1227,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1081,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1174,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1079,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1275,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1116,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1183,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1259,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1296,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1284,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1032,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1168,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1074,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1171,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1218,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1266,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1075,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1272,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1049,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1201,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1088,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1287,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1174,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1123,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1009,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1270,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1003,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1100,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1092,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1219,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1289,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1114,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1242,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1133,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1016,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1206,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1232,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1140,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1270,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1277,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1228,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1012,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1050,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1257,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1080,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1168,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1087,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1041,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1116,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1057,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1177,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1042,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1249,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1173,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1290,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1061,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1189,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1035,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1033,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1182,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1220,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1264,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1087,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1042,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1044,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1280,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1300,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1053,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1199,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1155,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1139,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1213,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1114,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1066,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1234,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1008,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1018,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1046,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1235,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1070,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1030,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1234,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1010,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1032,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1112,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1298,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1055,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1124,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1119,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1243,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1265,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1028,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1112,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1300,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1242,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1146,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1122,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1238,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1251,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1034,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1259,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1266,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1124,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1072,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1042,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1235,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1029,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1008,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1104,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1199,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1268,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1221,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1071,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1279,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1175,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1033,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1173,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1203,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1061,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1242,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1162,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1121,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1071,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1130,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1002,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1150,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1137,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1188,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1237,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1023,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1104,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1081,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1161,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1021,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1005,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1280,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1244,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1177,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1293,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1102,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1041,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1273,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1245,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1217,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1013,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1209,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1225,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1212,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1059,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1114,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1076,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1136,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1071,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1005,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1162,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1194,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1214,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1077,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1110,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1039,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1203,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1165,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1254,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1244,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1187,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1031,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1050,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1235,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1102,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1269,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1147,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1282,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1072,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1102,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1053,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1203,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1010,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1227,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1233,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1145,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1069,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1191,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1246,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1251,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1294,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1003,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1100,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1078,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1218,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1179,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1045,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1183,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1176,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1220,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1107,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1234,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1100,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1172,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1117,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1119,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1120,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1011,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1111,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1078,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1249,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1235,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1248,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1248,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1016,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1028,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1256,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1013,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1230,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1036,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1229,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1216,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1044,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1054,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1065,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1152,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1272,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1166,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1220,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1137,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1160,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1019,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1025,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1215,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1101,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1055,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1250,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1246,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1249,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1299,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1265,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1147,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1287,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1180,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1060,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1025,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1040,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1242,'Independent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1273,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1151,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1271,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1018,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1020,'Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1256,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1172,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1053,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1040,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1244,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1185,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1157,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1187,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1053,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1064,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1275,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1210,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1030,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1173,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1034,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1070,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1153,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1134,'Romance');
INSERT INTO Genres(MovieID,GenreName) VALUES (1173,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1254,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1034,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1203,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1018,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1098,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1039,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1029,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1007,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1202,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1271,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1295,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1278,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1073,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1297,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1221,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1244,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1155,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1269,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1266,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1041,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1078,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1206,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1013,'Musical');
INSERT INTO Genres(MovieID,GenreName) VALUES (1158,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1250,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1107,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1292,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1204,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1077,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1225,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1265,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1146,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1067,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1198,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1267,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1168,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1124,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1039,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1229,'Bollywood');
INSERT INTO Genres(MovieID,GenreName) VALUES (1273,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1039,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1075,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1102,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1034,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1148,'Thriller');
INSERT INTO Genres(MovieID,GenreName) VALUES (1179,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1122,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1037,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1197,'Action');
INSERT INTO Genres(MovieID,GenreName) VALUES (1025,'Parody');
INSERT INTO Genres(MovieID,GenreName) VALUES (1136,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1026,'Martial Arts');
INSERT INTO Genres(MovieID,GenreName) VALUES (1141,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1085,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1066,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1202,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1252,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1053,'Science Fiction');
INSERT INTO Genres(MovieID,GenreName) VALUES (1184,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1238,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1289,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1058,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1016,'Horror');
INSERT INTO Genres(MovieID,GenreName) VALUES (1222,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1241,'Mystery');
INSERT INTO Genres(MovieID,GenreName) VALUES (1115,'Western');
INSERT INTO Genres(MovieID,GenreName) VALUES (1284,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1193,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1005,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1203,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1065,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1291,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1295,'Adventure');
INSERT INTO Genres(MovieID,GenreName) VALUES (1153,'Fantasy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1158,'Animation');
INSERT INTO Genres(MovieID,GenreName) VALUES (1111,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1251,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1265,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1068,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1276,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1187,'Documentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1294,'Foreign Language');
INSERT INTO Genres(MovieID,GenreName) VALUES (1077,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1231,'Black Comedy');
INSERT INTO Genres(MovieID,GenreName) VALUES (1295,'Slasher');
INSERT INTO Genres(MovieID,GenreName) VALUES (1232,'Historical Period');
INSERT INTO Genres(MovieID,GenreName) VALUES (1118,'Satire');
INSERT INTO Genres(MovieID,GenreName) VALUES (1203,'Silent');
INSERT INTO Genres(MovieID,GenreName) VALUES (1078,'Film Noir');
INSERT INTO Genres(MovieID,GenreName) VALUES (1190,'Mockumentary');
INSERT INTO Genres(MovieID,GenreName) VALUES (1299,'Drama');
INSERT INTO Genres(MovieID,GenreName) VALUES (1226,'Family Friendly');
INSERT INTO Genres(MovieID,GenreName) VALUES (1151,'Cult Classic');
INSERT INTO Genres(MovieID,GenreName) VALUES (1246,'Romance');
