DROP TABLE IF EXISTS Titles;
CREATE TABLE IF NOT EXISTS Titles(
   MovieID     INTEGER  NOT NULL PRIMARY KEY 
  ,Title       VARCHAR(36) NOT NULL
  ,Rating      VARCHAR(4) NOT NULL
  ,ReleaseYear INTEGER  NOT NULL
);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1001,'Human Of The Ancestors','G',1969);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1002,'Horse Of The Great','G',1981);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1003,'Vultures Of The Lost Ones','G',1957);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1004,'Fish Of The West','G',2014);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1005,'Foes And Dogs','G',1958);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1006,'Turtles And Priests','G',1960);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1007,'Decay With Sins','G',1983);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1008,'Body With Strength','G',1958);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1009,'Hiding The Leaders','G',1943);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1010,'Changing The King','G',1979);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1011,'Serpent Of The Forsaken','G',1984);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1012,'Blacksmith Of Destruction','G',2001);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1013,'Fish Of Utopia','PG',1988);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1014,'Knights Of The Void','PG',1972);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1015,'Girls And Horses','PG',1940);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1016,'Boys And Creators','PG',1988);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1017,'Limit Of Utopia','PG',2016);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1018,'Luck Of The Frontline','PG',2007);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1019,'Blinded By The Fires','PG',1996);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1020,'Painting The Void','PG',1992);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1021,'King Of The Light','PG',1958);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1022,'Dog Of The Curse','PG',1985);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1023,'Defenders Without Honor','PG',1989);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1024,'Robots Of The Gods','PG',1970);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1025,'Wives And Companions','PG',2018);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1026,'Lions And Soldiers','PG',1952);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1027,'Completion Of Joy','PG',1995);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1028,'Decay Of The Banished','PG',1955);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1029,'Signs Of The Commander','PG',1958);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1030,'Question The Swamp','PG',1969);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1031,'Baker Of Sorrow','PG',1945);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1032,'Vulture Of Darkness','PG',2014);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1033,'Serpents Of Freedom','PG13',2002);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1034,'Descendants Of Freedom','PG13',1949);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1035,'Men And Vultures','PG13',2012);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1036,'Friends And Friends','PG13',1973);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1037,'Nation Of The South','PG13',1940);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1038,'Concept Without Glory','PG13',1958);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1039,'Listening To The Beginning','PG13',1941);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1040,'Eating At A Storm','PG13',1963);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1041,'Wolf Of Stone','PG13',1995);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1042,'Stranger Of Utopia','PG13',1965);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1043,'Defenders Without Shame','PG13',1955);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1044,'Defenders Of The South','PG13',1945);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1045,'Phantoms And Men','PG13',2010);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1046,'Children And Butchers','PG13',1978);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1047,'Disruption Of The Prison','PG13',1982);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1048,'Loss With Honor','PG13',1977);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1049,'Praised By The Elements','PG13',2011);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1050,'Symbols Of My Past','PG13',1965);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1051,'Human Of The Land','PG13',1976);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1052,'Fish Of The Ancients','PG13',1997);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1053,'Traitors Without Fear','PG13',1953);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1054,'Turtles Of Power','PG13',2014);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1055,'Aliens And Companions','PG13',1973);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1056,'Thieves And Guardians','PG13',1969);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1057,'Victory Of The Stars','PG13',2002);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1058,'Fruit With Honor','PG13',1975);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1059,'Temptations Of My Family','PG13',1968);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1060,'Lurking In The Country','PG13',2009);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1061,'Spy Without A Goal','PG13',1947);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1062,'Rat With Immortality','PG13',1996);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1063,'Spies Of The Night','PG13',2008);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1064,'Women With Strength','PG13',1960);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1065,'Butchers And Criminals','PG13',1963);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1066,'Priests And Heirs','PG13',1964);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1067,'Faith Of The Plague','PG13',1957);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1068,'Name Of The Ancestors','PG13',1989);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1069,'Mending The Sea','PG13',1952);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1070,'Traces In The Forest','PG13',1963);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1071,'Raven With Silver','PG13',1969);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1072,'Witch Of Dusk','PG13',1998);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1073,'Girls With Honor','PG13',2006);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1074,'Spiders Without Direction','PG13',1968);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1075,'Creators And Cats','PG13',1979);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1076,'Strangers And Kings','PG13',1976);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1077,'Goal Of Wind','PG13',2014);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1078,'Defeat Of Silver','PG13',1960);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1079,'Flying Into The Town','PG13',1981);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1080,'Escape The Forest','PG13',1998);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1081,'Thief Of The Forest','PG13',2014);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1082,'Butcher Of Dusk','PG13',1985);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1083,'Cats Without Desire','PG13',1973);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1084,'Guardians Without Glory','PG13',1970);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1085,'Children And Owls','PG13',1962);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1086,'Defenders And Turtles','PG13',1941);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1087,'Luck Of The Forsaken','PG13',1958);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1088,'Hope With Determination','PG13',2013);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1089,'Laughing At The Sea','PG13',1986);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1090,'Challenge Of The Maze','PG13',1957);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1091,'Baker Gamble','PG13',1970);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1092,'Criminal Left Me','PG13',1967);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1093,'Stranger Program','PG13',1968);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1094,'Angel Scheme','PG13',1978);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1095,'Mime And Companion','PG13',1973);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1096,'Prankster And Fish','PG13',1989);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1097,'Tricking In The Museum','PG13',1954);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1098,'Humor Stalks Me','PG13',1976);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1099,'Charm Of Fantasy','PG13',1987);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1100,'Power Of The Boy','PG13',1988);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1101,'Pig Mocks Me','PG13',1959);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1102,'Man In The Hallway','PG13',1993);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1103,'Knight Can Sing','PG13',1957);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1104,'Parrot Job','PG13',1942);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1105,'Officer And Stranger','PG13',1977);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1106,'Raven And Queen','PG13',1940);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1107,'Traps During The Night','PG13',1999);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1108,'Trouble Has Been Naughty','PG13',2000);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1109,'Song Of The Sisters','PG13',2007);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1110,'Song Of That Girl','PG13',1982);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1111,'Knight Stalks Me','PG13',1978);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1112,'King And My Journey','PG13',1978);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1113,'Girl Can Dance','PG13',1997);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1114,'Parrot In The Window','PG13',1956);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1115,'Rat And Agent','PG13',2005);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1116,'Agent And Child','PG13',1963);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1117,'Tricks Of Stunts','PG13',1967);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1118,'Humor Setup','PG13',1975);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1119,'Charm Of The Job','PG13',1997);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1120,'Love For Fire','PG13',2013);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1121,'Vulture Asks Weird Questions','PG13',1960);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1122,'Monk With Rotten Skin','PG13',1962);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1123,'Creatures With Rotten Skin','PG13',1970);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1124,'Imps Under My Bed','PG13',2013);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1125,'Teachers And Imps','R',1975);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1126,'Children And Boys','R',1966);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1127,'Hidden In The Library','R',1942);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1128,'Sounds In The Antique Shop','R',2002);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1129,'Weeping At The End','R',2011);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1130,'Humble In My Nightmares','R',1977);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1131,'Crow Hiding From Me','R',1999);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1132,'Skeleton With A Smile','R',1968);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1133,'Beasts During Lunch','R',1957);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1134,'Men In The Attic','R',1967);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1135,'Snakes And Agents','R',1989);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1136,'Ghosts And Bats','R',1951);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1137,'Signs At The River','R',1946);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1138,'Captured At The Tombs','R',1981);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1139,'Defenseless In The Sea','R',1954);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1140,'Humble In The Country','R',2010);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1141,'Leader Of Our Future','R',1957);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1142,'Figure Of Sunshine','R',1962);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1143,'Strangers Of The Vacuum','R',1942);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1144,'Hunters Of War','R',1991);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1145,'Strangers And Creatures','R',1991);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1146,'Rebels And Medics','R',1987);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1147,'Reincarnation From Outer Space','R',2004);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1148,'Planet From Outer Space','R',1946);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1149,'Life With The Truth','R',1958);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1150,'Serenity Of Technology','R',1982);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1151,'Rebel Of Our Legacy','R',2014);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1152,'Woman Of The Past','R',1996);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1153,'Recruits Of New Worlds','R',1979);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1154,'Martians Of Space','R',1983);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1155,'Assassins And Doctors','R',2004);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1156,'Invaders And Aliens','R',1990);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1157,'Doom Of The Faceless Ones','R',2005);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1158,'Death Of The Void','R',1951);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1159,'Puzzle Of The Vacuum','R',1967);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1160,'Mother Of The Moon','R',2014);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1161,'Defender Of The Future','R',1997);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1162,'Figure In The Future','R',1966);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1163,'Officers Of Honor','R',1971);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1164,'Directors In The Center Of The Earth','R',2013);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1165,'Heroes And Clones','R',1972);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1166,'Soldiers And Guests','R',1942);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1167,'Construction Of The Past','R',1980);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1168,'Destiny Of The Dead','R',1991);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1169,'Right For The Vacuum','R',2013);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1170,'Changed By The Portal','R',1990);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1171,'God Of The Solstice','R',1965);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1172,'Duke Of Freedom','R',2014);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1173,'Heartthrobs In My Town','R',2001);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1174,'Strangers With Brown Hair','R',2001);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1175,'Valentines And Gods','R',2009);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1176,'Sweethearts And Angels','R',1957);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1177,'Lust Of The West','R',1990);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1178,'Accident In The Forest','R',1974);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1179,'Symbols Of The River','R',1952);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1180,'Accepting My Friend','R',1980);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1181,'Farmer Of The Night','R',1944);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1182,'Companion Without Hope','R',1975);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1183,'Opponents Of The Stockades','R',2013);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1184,'Assassins With A Goal','R',1972);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1185,'Horses And Armies','R',1957);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1186,'Invaders And Deputies','R',1997);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1187,'End Of War','R',1970);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1188,'Disruption Without Faith','R',1964);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1189,'Prepare For The Abyss','R',1992);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1190,'Losing Secrets','R',1948);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1191,'Doctor Without A Conscience','R',1983);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1192,'Collector With Horns','R',2015);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1193,'Supporters Of Ice','NR',2000);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1194,'Inventors Dressed In Black','NR',1993);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1195,'Farmers And Assassins','NR',1954);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1196,'People And Bearers','NR',1996);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1197,'Country Of The West','NR',2001);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1198,'Birth Of The Forest','NR',1966);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1199,'Listening To The King','NR',1981);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1200,'Mending The Jungle','NR',1943);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1201,'Goat Of Wood','NR',1981);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1202,'Bunny Of Yesterday','NR',1959);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1203,'Kings Of Riddles','NR',1978);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1204,'Wizards Of Riddles','NR',1991);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1205,'Puppies And Little Birds','NR',1950);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1206,'Sheep And Boys','NR',2002);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1207,'Statue Of The Sun','NR',1960);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1208,'Roof Of Silver','NR',1987);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1209,'Caring For My Pet Dragon','NR',1959);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1210,'Learning With Leaves','NR',1987);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1211,'Amphibians Of Tomorrow','NR',1974);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1212,'Leaders Per Country','NR',1940);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1213,'Spiders Of The Depths','NR',1975);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1214,'Corals Of The North','G',1972);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1215,'Birds And Dinosaurs','G',1991);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1216,'Horses And Enemies','G',1964);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1217,'Fantasy Of The Revolution','G',1959);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1218,'Planes Of Time','G',1949);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1219,'Broken Cooking','G',1995);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1220,'Curse Of Your Home','G',1955);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1221,'Freaks Of Dreams','G',2001);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1222,'Trees Of Technology','G',1955);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1223,'Fish Of Our Realm','G',1999);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1224,'Horses Of The West','G',2015);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1225,'Fungi And Followers','G',1947);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1226,'Preys And Athletes','G',2004);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1227,'Silver Of The Future','G',2015);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1228,'Castles Of The West','G',1943);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1229,'Amusing Aliens','G',1967);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1230,'Focus On Your Garden','G',1965);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1231,'Fools With Tradition','G',2015);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1232,'Women With Skills','G',1971);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1233,'Children Around The World','G',1973);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1234,'Fungi Of The Swamp','G',1968);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1235,'Angels And Ancestors','G',1982);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1236,'Rats And Queens','G',2017);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1237,'Sins Of Magic','G',2006);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1238,'Robots Of The Revolution','G',1950);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1239,'Blinded By Your Family','G',1971);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1240,'Creative Time Travel','G',1966);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1241,'Leaders Per Continent','G',2016);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1242,'Dogs Of The Caves','G',1947);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1243,'Freaks Of The Sky','G',1968);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1244,'Sinners Of The Jungle','G',1961);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1245,'Flowers And Corals','G',1961);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1246,'Children And Moons','G',1973);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1247,'Societies In Your Garden','G',1943);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1248,'Harvest Of The Swamp','G',1994);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1249,'The Best The Lands','G',1948);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1250,'Harmful Robots','G',2002);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1251,'Flies Of Yesterday','G',1955);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1252,'Women Of Medicine','PG13',1993);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1253,'Preys Per Realm','PG13',2002);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1254,'Emperors Of Yesterday','PG13',2001);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1255,'Birds And Spiders','PG13',2000);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1256,'Cats And Fungi','PG13',1948);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1257,'Disasters With Skills','PG13',1961);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1258,'Working Of The Decade','PG13',2007);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1259,'Friends Of Aliens','PG13',1952);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1260,'Excellence Of Space','PG13',2016);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1261,'Politicians Of The South','PG13',2017);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1262,'Kings Of The Swamp','PG13',1947);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1263,'Followers Of The Planet','PG13',1941);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1264,'Ancients Per Continent','PG13',1952);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1265,'Flowers And Crustaceans','PG13',1956);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1266,'Rats And Demons','PG13',1973);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1267,'Castles Of The World','PG13',2018);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1268,'Languages Of The Past','PG13',2018);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1269,'Innocence Of Painting','PG13',1995);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1270,'Respect For The Forest','PG13',1975);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1271,'Crustaceans With Skills','PG13',1967);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1272,'Flowers Of Heaven','PG13',2018);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1273,'Friends Without Borders','PG13',2007);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1274,'Herbs Of Our Realm','PG13',1978);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1275,'Snakes And Ancients','PG13',1965);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1276,'Friends And Snakes','PG13',1959);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1277,'Iron Of Our Realm','PG13',1973);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1278,'Signs With Style','PG13',1940);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1279,'Annual Biology','PG13',1977);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1280,'Unusual Neverland','PG13',1997);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1281,'Rage Cage','PG13',1962);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1282,'Zombie Portraits','PG13',2012);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1283,'Super Lobster and Friends','PG13',1959);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1284,'My Fun Spleen','PG13',1963);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1285,'Christmas in Zimbwe','PG13',1984);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1286,'Jupiter Collision','PG13',1982);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1287,'It Came from France','PG13',2012);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1288,'Happy Slap Day','PG13',1993);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1289,'We Eat Soup','PG13',1943);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1290,'Today Gravy','PG13',1951);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1291,'Similar Words','PG13',1990);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1292,'Nautical Pants','PG13',1971);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1293,'Ships of Summer','PG13',1969);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1294,'Slightly Explosive','PG13',2008);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1295,'Every Burger','PG13',1968);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1296,'Kings of Cat','PG13',1962);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1297,'Music of the North','PG13',2004);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1298,'Killer Ice Cubes','PG13',1999);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1299,'Queen of Jump','PG13',1958);
INSERT INTO Titles(MovieID,Title,Rating,ReleaseYear) VALUES (1300,'Unique New York','PG13',1941);
