DROP TABLE IF EXISTS Users;
CREATE TABLE IF NOT EXISTS Users(
   UserID INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,Name   VARCHAR(40) NOT NULL
)AUTO_INCREMENT=1001;
INSERT INTO Users(UserID,Name) VALUES (1001,'Serita');
INSERT INTO Users(UserID,Name) VALUES (1002,'Zina');
INSERT INTO Users(UserID,Name) VALUES (1003,'Queen');
INSERT INTO Users(UserID,Name) VALUES (1004,'Lura');
INSERT INTO Users(UserID,Name) VALUES (1005,'Amada');
